connection:
  username : admin
  remoteAddress : "192.168.1.1"
logging:
  level:
    org.springframework.web: debug
    org.hibernate: error

#spring boot默认会加载classpath:logback-spring.xml或者classpath:logback-spring.groovy

